name: Bug Report 🐛
description: Report a bug
labels: ["bug","IWOC2024"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help everyone identify and fix the bug
  - type: textarea
    id: description
    attributes:
      label: Describe your issue
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: A clear and concise description of what you expected to happen.
  - type: textarea
    id: screenshots
    attributes:
      label: Put here any screenshots or videos (optional)
  - type: textarea
    id: contact
    attributes:
      label: How can we contact you (optional)
      placeholder: |
        Leave your discord or social media handle
    validations:
      required: false
  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "Yes"
        - "No"
  - type: checkboxes
    id: terms
    attributes:
      label: "By submitting this issue, I have confirmed that:"
      options:
        - label: I have starred the repo ⭐
          required: true
        
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.